<a href="https://colab.research.google.com/github/jainary4/Word_Prediction_LLM_LSTM_model/blob/main/Word_Prediction_LSTM_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
faqs = """About the Program
What is the course fee for  Data Science Mentorship Program (DSMP 2023)
The course follows a monthly subscription model where you have to make monthly payments of Rs 799/month.
What is the total duration of the course?
The total duration of the course is 7 months. So the total course fee becomes 799*7 = Rs 5600(approx.)
What is the syllabus of the mentorship program?
We will be covering the following modules:
Python Fundamentals
Python libraries for Data Science
Data Analysis
SQL for Data Science
Maths for Machine Learning
ML Algorithms
Practical ML
MLOPs
Case studies
You can check the detailed syllabus here - https://learnwith.campusx.in/courses/CampusX-Data-Science-Mentorship-Program-637339afe4b0615a1bbed390
Will Deep Learning and NLP be a part of this program?
No, NLP and Deep Learning both are not a part of this program’s curriculum.
What if I miss a live session? Will I get a recording of the session?
Yes all our sessions are recorded, so even if you miss a session you can go back and watch the recording.
Where can I find the class schedule?
Checkout this google sheet to see month by month time table of the course - https://docs.google.com/spreadsheets/d/16OoTax_A6ORAeCg4emgexhqqPv3noQPYKU7RJ6ArOzk/edit?usp=sharing.
What is the time duration of all the live sessions?
Roughly, all the sessions last 2 hours.
What is the language spoken by the instructor during the sessions?
Hinglish
How will I be informed about the upcoming class?
You will get a mail from our side before every paid session once you become a paid user.
Can I do this course if I am from a non-tech background?
Yes, absolutely.
I am late, can I join the program in the middle?
Absolutely, you can join the program anytime.
If I join/pay in the middle, will I be able to see all the past lectures?
Yes, once you make the payment you will be able to see all the past content in your dashboard.
Where do I have to submit the task?
You don’t have to submit the task. We will provide you with the solutions, you have to self evaluate the task yourself.
Will we do case studies in the program?
Yes.
Where can we contact you?
You can mail us at nitish.campusx@gmail.com
Payment/Registration related questions
Where do we have to make our payments? Your YouTube channel or website?
You have to make all your monthly payments on our website. Here is the link for our website - https://learnwith.campusx.in/
Can we pay the entire amount of Rs 5600 all at once?
Unfortunately no, the program follows a monthly subscription model.
What is the validity of monthly subscription? Suppose if I pay on 15th Jan, then do I have to pay again on 1st Feb or 15th Feb
15th Feb. The validity period is 30 days from the day you make the payment. So essentially you can join anytime you don’t have to wait for a month to end.
What if I don’t like the course after making the payment. What is the refund policy?
You get a 7 days refund period from the day you have made the payment.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmail.com
Post registration queries
Till when can I view the paid videos on the website?
This one is tricky, so read carefully. You can watch the videos till your subscription is valid. Suppose you have purchased subscription on 21st Jan, you will be able to watch all the past paid sessions in the period of 21st Jan to 20th Feb. But after 21st Feb you will have to purchase the subscription again.
But once the course is over and you have paid us Rs 5600(or 7 installments of Rs 799) you will be able to watch the paid sessions till Aug 2024.
Why lifetime validity is not provided?
Because of the low course fee.
Where can I reach out in case of a doubt after the session?
You will have to fill a google form provided in your dashboard and our team will contact you for a 1 on 1 doubt clearance session
If I join the program late, can I still ask past week doubts?
Yes, just select past week doubt in the doubt clearance google form.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmai.com
Certificate and Placement Assistance related queries
What is the criteria to get the certificate?
There are 2 criterias:
You have to pay the entire fee of Rs 5600
You have to attempt all the course assessments.
I am joining late. How can I pay payment of the earlier months?
You will get a link to pay fee of earlier months in your dashboard once you pay for the current month.
I have read that Placement assistance is a part of this program. What comes under Placement assistance?
This is to clarify that Placement assistance does not mean Placement guarantee. So we dont guarantee you any jobs or for that matter even interview calls. So if you are planning to join this course just for placements, I am afraid you will be disappointed. Here is what comes under placement assistance
Portfolio Building sessions
Soft skill sessions
Sessions with industry mentors
Discussion on Job hunting strategies
In the ideological  landscape of the 20th century, marked by the erosion of traditional certitudes and the rise of the modern self, literature reflects the profound changes in society and human consciousness. The provided quotes from various texts show  the panic, anxiety, and warnings associated with this transition. Furthermore, they serve as powerful illustrations of how mass production, mass consumption, and mass advertising have redefined the sacred, creating commodities that promise the illusion of the PEPSI myths: Perfection, Efficiency, Progress, Satisfaction, and Innovation, all while leaving them just out of reach in an uncertain future. These quotes take us through a  journey of transition in the way our civilization centers its beliefs and practices. These quotes take us through a journey of transition from the Age of Faith to the Age of Science.
In the Texts and Arguments presented in the lecture we discuss a transition from the “Age of Faith” to the “Age of Science”. This discussion is at the heart of all the ideas discussed in the class and in this essay. As our world progressed towards the “Age of Science” many older ideas about life, way of living and human relationships were replaced with new interpretations and meanings. Analyzing the texts presented in the class, one sharp change in society highlighted by all the great authors over the centuries is a shift from the “soul” to the “self”. As our society changed from a “Religious view” to a “Scientific view” individualism and selfishness grew in society.
This is very evident from the melancholic tone of “Dover Beach” by Matthew Arnold. The poem starts by describing a calming  and peaceful scene by the sea at night which symbolizes the quiet and calming times when faith used to prevail the world, as the poem progresses the tone changes from calmness to melancholy which symbolizes the changing world where faith is eroding, people are becoming more and more  materialistic and there is a state of uncertainty in the world. This poem provides us with a way to understand how human civilization shifted from the “soul” to  a “self” mentality.
The PEPSI myth discussed in the class is very relevant with the modern idea of the world. The world has become a lot more self-centered and goal oriented. With the advent of industrialization and capitalism ideas like efficiency, progress , perfection and innovation are embraced by society. A classic example of the way young adults operate in modern society is given by Bret Easton Ellis’s “American Psycho”. In the novel the author describes the protagonist to be a self-centered man , who, like Dorian Gray, is obsessed with his flawless appearance and always strives to achieve perfection in his appearance by following a detailed morning skin-care routine. These descriptions show us the transition to “self” as the age of science took over the world.
We now move on to discuss the ideas behind the Quotes described in the texts that were presented in the class:
Quote One from Oscar Wilde's "The Picture of Dorian Gray" encapsulates the seductive nature of self-fulfillment at the expense of others . Dorian's rejection of Sibyl Vane just because she didn't perform well in front of his friends reflects his relentless pursuit of personal satisfaction and perfection. His declaration that "Without your art, you are nothing" underscores the materialism of human relationships, where individuals are valued solely for their ability to enhance themselves. This shows us the fact that human relationships are just like markets, in the sense that  “You are relevant as long as you are skilled”. This mirrors the commodification of products in a consumer-driven society, where satisfaction and perfection are perpetually tried to be achieved.
Quote Two from Matthew Arnold's "Dover Beach" paints a bleak picture of a world where the "Sea of Faith" has receded, leaving behind a dark and uncertain landscape. Arnold is asking people to be honest and real with each other in a world that's uncertain and chaotic because he believes that real connections and authenticity are important. The absence of joy, love, and light in this new world parallels the way commodities promise satisfaction and perfection but fail to deliver, perpetuating a sense of emptiness. The poem by Matthew Arnold paints a picture of changing times where he explores how ideas of faith and certainty are fading away from society.
Quote Three from W.B. Yeats' "The Second Coming" vividly paints a picture of a  world spiraling into anarchy, where the "center cannot hold," and innocence is drowned. The image of a falcon turning in a widening circle without being able to hear its falconer represents a sense of detachment and disconnection. The poem also talks about how the best people lack conviction and determination, while the worst people are full of passionate intensity. This tells us  that those who should be responsible and wise are unsure or passive, while those who are more destructive are driven by strong and passionate beliefs. This chaos mirrors the dissatisfaction  that often accompanies the pursuit of the PEPSI myths, which promise progress and innovation but deliver only turmoil and an unattainable goal. People are stuck running in a race with no finish line.
Quote Four from Joseph Conrad's "Heart of Darkness'' delves into the consequences of relentless pursuit. Kurtz seeks justice and recognition in the Congo but descends into madness and obsession. The repetition of "The horror! The horror!" underscores the destructive nature of his quest, mirroring the emptiness of pursuing the PEPSI myths. His Intended desire to cling to his memory despite the horrors he embodied symbolizes society's willingness to embrace the allure of progress and innovation while turning a blind eye to the ethical costs.
In the context of the above quotes and the idea of the shift from the “Age of Faith” to the “Age of Science” we observe an increase of materialism in the world. Also as the world moved towards the “Age of Science” there was an increase in uncertainty in the world as marked by Matthew Arnold’s poem. New ideas of  mass production, mass consumption, and mass advertising became more and more prominent as the world grew more and more capitalistic. These ideas compelled people to work towards earning a living, build their homes, and build a bigger bank balance. But a philosophical question is still left unanswered: Why ? Why are people running in their lives to achieve a dream lifestyle? In this part we discuss the central themes of the “Age of Science”  or in other terms the “Age of Anxiety”. The PEPSI myths is, what I believe, the cause of the capitalistic world today. Every individual is working their way to achieve exactly what the PEPSI myth tells us. Below we discuss the ideas of mass production and the modern capitalism in detail.
 At the heart of the modern age is the concept of mass production. This paradigm shift revolutionized the way goods were manufactured, leading to an abundance of products. The assembly line, pioneered by Henry Ford, enabled the efficient production of automobiles, a symbol of progress and innovation. This newfound abundance created a sense of optimism, with people believing that mass production would bring about a utopian society characterized by perfection and efficiency.
However, the reality was far more complex. Mass production not only altered the economic landscape but also transformed cultural and social dynamics. The emphasis on quantity often came at the expense of quality, leading to the commodification of products. Items that were once considered rare and valuable became commonplace, diminishing their sacredness. This transition mirrors Dorian Gray's obsession with art and beauty, believing they were the key to his self-worth. In this context, commodities became extensions of the self, reinforcing the pursuit of perfection and satisfaction.
Mass production gave birth to mass consumption, creating a culture where acquiring commodities became synonymous with personal success and happiness. Advertisers played a pivotal role in promoting this ideology, employing persuasive techniques to convince consumers that they needed the latest products to enhance their lives. The commodification of desire fueled a relentless pursuit of satisfaction, mirroring Dorian's obsession with his own image and the shallow pursuit of self-fulfillment.
This relentless quest for satisfaction often led to disillusionment, echoing Matthew Arnold's portrayal of a world where the "Sea of Faith" had receded, leaving individuals adrift in a landscape devoid of certitude. The promised joy, love, and light associated with commodities remained elusive, perpetuating a sense of emptiness and disconnection. Despite the abundance of material goods, individuals struggled to find meaning and authenticity in a world driven by consumption.
Mass advertising emerged as a powerful force shaping the modern self. Advertisers tapped into the collective anxieties and desires of society, promising that commodities held the key to progress, innovation, and efficiency. The allure of these promises, often perpetually deferred, paralleled the anxieties expressed in W.B. Yeats' "The Second Coming." The center could not hold, and the ceremony of innocence was drowned in a sea of advertising messages that fueled passionate intensity in the pursuit of material satisfaction.
In conclusion, the provided quotes offer insights into the 19th and 20th-century crisis of the self. The discussion of how the world changed to the “Age of Science” from the “Age of Faith” served by the various quotes discussed in the course provide us with a more broader picture of the progression of our modern history and how our current views are shaped from a few fundamental core beliefs adopted by our society as a whole.  As our world progresses ideas like Mass production, mass consumption, and mass advertising have reshaped the way our civilization thinks, works and most importantly connects with each other. At the most fundamental level this essay is about showing that in the “Age of Science” people connect with others on a need basis, our relationship with others is based on their need in our life. This ideology of the basis of relationships today shows a sharp change from the “Age of Faith” where people connected with each other on a spiritual level, there was faith , there was belief in people for other people and for the world as a whole.

"""

In [2]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
#Our task is to build a model that can predict words for us, this is essentially a word generator
# we first tokenize the data , which assigns a uniqe number to every unique word thereby tokenizing every word in the dataset
# we can use the word index function to look at the word dictionary

tokenizer = Tokenizer()

In [3]:
tokenizer.fit_on_texts([faqs])
tokenizer.word_index


{'the': 1,
 'of': 2,
 'and': 3,
 'a': 4,
 'to': 5,
 'in': 6,
 'you': 7,
 'is': 8,
 'i': 9,
 'this': 10,
 'are': 11,
 'from': 12,
 'world': 13,
 'have': 14,
 'by': 15,
 'with': 16,
 'that': 17,
 'what': 18,
 'will': 19,
 'our': 20,
 'mass': 21,
 'where': 22,
 'can': 23,
 'for': 24,
 'on': 25,
 'as': 26,
 'course': 27,
 'we': 28,
 'be': 29,
 'all': 30,
 'us': 31,
 '“age': 32,
 'people': 33,
 'program': 34,
 'society': 35,
 'self': 36,
 'at': 37,
 'more': 38,
 'his': 39,
 'sessions': 40,
 'production': 41,
 'ideas': 42,
 'if': 43,
 'how': 44,
 'am': 45,
 'pay': 46,
 'payment': 47,
 'perfection': 48,
 'satisfaction': 49,
 'way': 50,
 'make': 51,
 'not': 52,
 'do': 53,
 'able': 54,
 'your': 55,
 'but': 56,
 'modern': 57,
 'quotes': 58,
 'faith': 59,
 'science”': 60,
 'pursuit': 61,
 'their': 62,
 'about': 63,
 'science': 64,
 'subscription': 65,
 'rs': 66,
 'so': 67,
 'campusx': 68,
 'session': 69,
 'class': 70,
 'paid': 71,
 'once': 72,
 'join': 73,
 'or': 74,
 'website': 75,
 'placement':

In [4]:
len(tokenizer.word_index)

819

In [5]:
# our main task in the first half is to create the input - output dataset from the word document
# the input data set contains the vector representation of sentence pieces so for example we have a sentence "I am Aryan"
# the input dataset will have "I" , "I am" and "I am Aryan" in the input dataset ,the output dataset contains the next word that comes in the sentence piece
# here we first split the input text based on \n so we divide it into sentences and then give the vector version of the sentences using text_to_sequence method
# we then start a loop to get sentence slices starting the first word and going until the end of the sentence
# the data set input_sequences is built as such that from index 0 - {len(sentence)-1} are the entries belonging to the input data set
# the last entry gives us the output of every sentence slice


input_sequences = []
for sentence in faqs.split('\n'):
  tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]

  for i in range(1,len(tokenized_sentence)):
    input_sequences.append(tokenized_sentence[:i+1])

In [6]:
input_sequences[0:20]

[[63, 1],
 [63, 1, 34],
 [18, 8],
 [18, 8, 1],
 [18, 8, 1, 27],
 [18, 8, 1, 27, 83],
 [18, 8, 1, 27, 83, 24],
 [18, 8, 1, 27, 83, 24, 84],
 [18, 8, 1, 27, 83, 24, 84, 64],
 [18, 8, 1, 27, 83, 24, 84, 64, 133],
 [18, 8, 1, 27, 83, 24, 84, 64, 133, 34],
 [18, 8, 1, 27, 83, 24, 84, 64, 133, 34, 356],
 [18, 8, 1, 27, 83, 24, 84, 64, 133, 34, 356, 357],
 [1, 27],
 [1, 27, 196],
 [1, 27, 196, 4],
 [1, 27, 196, 4, 85],
 [1, 27, 196, 4, 85, 65],
 [1, 27, 196, 4, 85, 65, 197],
 [1, 27, 196, 4, 85, 65, 197, 22]]

In [7]:
max_len = max([len(x) for x in input_sequences])
#the vectors we obtain as the input sequence are not of the same length , we use padding to make them equal the size of the highest dimensional vector
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input_sequences = pad_sequences(input_sequences, maxlen = max_len, padding='pre')

In [8]:
print(padded_input_sequences)
#nested array of padded input sentence piece vectors

[[  0   0   0 ...   0  63   1]
 [  0   0   0 ...  63   1  34]
 [  0   0   0 ...   0  18   8]
 ...
 [  0   0   6 ...   1  13  26]
 [  0   6 794 ...  13  26   4]
 [  6 794   1 ...  26   4 351]]


In [9]:
output_nested_vector=[]
for vector in padded_input_sequences:
  x=vector[:-1]
  output_nested_vector.append(x)
print(output_nested_vector)
X=padded_input_sequences[:,:-1]
print(x)


[array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 63],
      dtype=int32), array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0, 

In [10]:
Y = padded_input_sequences[:,-1]
print(Y)
Y.shape

[  1  34   8 ...  26   4 351]


(2541,)

In [11]:
X.shape
# there are 2541 sentences and each sentence is padded to be of length 185
# when we are converting the data to a categorical regression problem we need to provide the same number of channels as the number of distinct words


(2541, 185)

In [12]:
from tensorflow.keras.utils import to_categorical
y = to_categorical(Y,num_classes=820)

In [17]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense
# after creating the input and output vectors we initialize the architecture of the model
# the first layer is an embedding layer, the embedding layer assignes a (100 X 1) vector to every tokenized word
# also we know that every sentence is represented by a padded 56X1 vector.
# every entry in the vector represents a tokenized word or the padding 0 now the embedding layer assignes a 100x1 vector to every tokenized vector entry
# then we send the output of the embedding layer to a 150 node LSTM network
# so in the LSTM input we send a 100 x 1 vector where each vector represents a tokenized word in the document which is in a  sentence vector of length 56 X 1
# the output of the LSTM layer is then sent through a dense layer where we use categorical cross entropy to find the output which is given by a hard-encoded vector
# so if the model predicts the next word to be of the tokenized index of 4 then the output is [0,0,0,1,0...0] we will get a 1 at that index
model = Sequential()
model.add(Embedding(820, 100, input_length=185))
model.add(LSTM(150))
model.add(Dense(820, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam',metrics=['accuracy'])
model.summary()
model.fit(X,y,epochs=3)

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 185, 100)          82000     
                                                                 
 lstm_2 (LSTM)               (None, 150)               150600    
                                                                 
 dense_2 (Dense)             (None, 820)               123820    
                                                                 
Total params: 356420 (1.36 MB)
Trainable params: 356420 (1.36 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
Epoch 1/3
80/80 [==============================] - 27s 307ms/step - loss: 6.2113 - accuracy: 0.0823
Epoch 2/3
80/80 [==============================] - 25s 311ms/step - loss: 5.7814 - accuracy: 0.0854
Epoch 3/3
80/80 [==============================] - 24s 306ms/step - loss: 5.6466 -

In [18]:
import time
import numpy as np
text = "I am"

for i in range(9):
  # tokenize
  token_text = tokenizer.texts_to_sequences([text])[0]
  padded_token_text = pad_sequences([token_text], maxlen=185, padding='pre')
  # predict
  pos = np.argmax(model.predict(padded_token_text))

  for word,index in tokenizer.word_index.items():
    if index == pos:
      text = text + " " + word
      print(text)
      time.sleep(2)


1/1 [==============================] - 0s 446ms/step
I am the
1/1 [==============================] - 0s 43ms/step
I am the the
1/1 [==============================] - 0s 46ms/step
I am the the of
1/1 [==============================] - 0s 46ms/step
I am the the of the
1/1 [==============================] - 0s 47ms/step
I am the the of the the
1/1 [==============================] - 0s 52ms/step
I am the the of the the of
1/1 [==============================] - 0s 72ms/step
I am the the of the the of the
1/1 [==============================] - 0s 102ms/step
I am the the of the the of the the
1/1 [==============================] - 0s 47ms/step
I am the the of the the of the the of
